configured_endpoints: 75
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/zeus%2Fhercules-ab619e600daf3e1c3180af1b56d0aa704cccf38dab9729e8974d0d65ca6bc628.yml
openapi_spec_hash: ad9c80c718ca0aa0fc1f2c7effacdd89
config_hash: f6ecd828e5e1b7be62ce1be74762d681
