name: Release Doctor
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  release_doctor:
    name: release doctor
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.repository == 'withzeusai/hercules-sdk-typescript' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release-please') || github.head_ref == 'next')

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Check release environment
        run: |
          bash ./bin/check-release-environment
